#!/bin/sh

# Shell script to collect desktop software data as an optional user-module.
# Copyright (C) 2001-2004 Open Challenge B.V.
# Copyright (C) 2004-2005 OpenEyeT Professional Services.
# Copyright (C) 2005-2018 QNH.
# Copyright (C) 2019 Siem Korteweg.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.
# If not, write to the Free Software Foundation,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#
# Created by Bill Dietrich
 
set -u
[ "${SCC_DEBUG:-}" ] && set -x

export ProgName=${0##*/}

if [ -z "${SCC_BIN:-}" -o -z "${SCC_CONF:-}" -o -z "${SCC_DATA:-}" ]
then
	echo "${ProgName}: activate this program via scc(1), scc-log(1) or scc-collect(1)" >&2
	exit 2
fi

if [ ! -w ${SCC_DATA} ]
then
	echo "${ProgName}: insufficient permissions to write in data directory: ${SCC_DATA}" >&2
	exit 2
fi

. ${SCC_BIN}/scc_modules/scc_utils




for d in /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin /opt
do
	if [ -d "${d}" ]
	then
		ftmp="/tmp/sccdirs.txt"
		ls -lAR --time-style=long-iso ${d} >${ftmp}
		scc_check_file "${ftmp}" "fix:software:desktop:${d}::" "#"
		rm ${ftmp}
	fi
done


# apt
f="/var/log/apt/history.log"
if [ -f ${f} ]
then
	scc_check_file "${f}" "fix:software:desktop:apt:${f}::" "#"
fi
f="/var/log/dpkg.log"
if [ -f ${f} ]
then
	ftmp="/tmp/scclog.txt"
	grep 'status installed' ${f} >${ftmp}
	scc_check_file "${ftmp}" "fix:software:desktop:dpkg:${f}::" "#"
	rm ${ftmp}
fi


exit 0

